
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import d from '../public/favicon.ico'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "../public/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../public/favicon.ico" sizes="any" />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
