
import Image from "next/image";
import type { Metadata } from "next";
import AppBar from '../components/Appbar'
import HeroSection from "@/components/HeroSection";
import HeroSection2 from "@/components/HeroSection2";
import Herosection3 from "@/components/Herosection3";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};
export default function Home() {
  return (
    <main>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <AppBar />
      <HeroSection />
      <HeroSection2 />
      <Herosection3 />
    </main>
  );
}
