
import Image from "next/image";
import type { Metadata } from "next";
import AppBar from '../components/Appbar'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};
export default function Home() {
  return (
    <main>
      <link rel="icon" href="/favicon.ico" sizes="any" />

      <AppBar />
    </main>
  );
}
